services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: jerry
      POSTGRES_PASSWORD: birthday
      POSTGRES_DB: memory_builder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: